export default {
	OK: "موافق",
	accessMaterials: "الوصول إلى المواد",
	addToMyList: "الإضافة إلى لائحتي",
	addedToMyLearningHeader: "تمت الإضافة بنجاح إلى تعلّمي",
	addedToYourList: "تمت الإضافة إلى لائحتك",
	all: "الكل",
	alreadyEnrolled: "تم التسجيل مسبقًا",
	backToDiscover: "العودة إلى أداة الاكتشاف",
	browseAllContent: "استعراض كل المحتوى",
	close: "إغلاق",
	continueBrowsing: "متابعة الاستعراض",
	courseCode: "رمز المقرر التعليمي",
	courseDescription: "وصف المقرر التعليمي",
	courseInfo: "معلومات حول المقرر التعليمي",
	coursePageDocumentTitle: "{courseName} - أداة الاكتشاف - {instanceName}",
	courseSummaryReadyMessage: "أصبح {courseTitle} جاهزًا الآن",
	discover: "أداة الاكتشاف",
	discoverHomeMessage: "هذه هي الصفحة الرئيسية لأداة الاكتشاف.",
	discovery: "الاكتشاف",
	durationMinutes: "{minutes} من الدقائق",
	emailFeedback: "إرسال ملاحظاتك عبر البريد الإلكتروني إلى {email}",
	endDate: "تاريخ الانتهاء",
	endDateIsInThePast: "تم إغلاق هذا المقرر التعليمي بتاريخ {date}.",
	enrollInCourse: "التسجيل في المقرر التعليمي",
	enrollmentHeaderFail: "فشل التسجيل",
	enrollmentHeaderPending: "التسجيل معلّق",
	enrollmentHeaderSuccess: "تم التسجيل بنجاح",
	enrollmentHeaderUnenrolled: "إمكانية الوصول غير متوفرة حاليًا",
	enrollmentMessageFail: "يتعذر التسجيل في هذا الوقت، يُرجى إعادة المحاولة لاحقًا.",
	enrollmentMessagePending: "إن تسجيلك في هذا المقرر التعليمي معلّق، يُرجى التحقق مجددًا في وقت لاحق للوصول إلى هذا المقرر التعليمي.",
	enrollmentMessageSuccess: "سيصبح {title} متوفرًا قريبًا في الأداة البرمجية مقرراتي التعليمية.",
	enrollmentMessageSuccessFuture: "سيصبح {title} متوفرًا في الأداة البرمجية مقرراتي التعليمية بتاريخ {date}",
	enrollmentMessageSuccessPast: "انتهى {title} بتاريخ {date}",
	enrollmentMessageUnenrolled: "لقد تم إلغاء تسجيلك من قبل مسؤول، تواصل مع المسؤول عنك للتسجيل مرة أخرى.",
	enrollmentOptions: "خيارات التسجيل",
	firstPublished: "تاريخ النشر الأول",
	homepageDocumentTitle: "أداة الاكتشاف - {instanceName}",
	lastUpdatedDate: "تاريخ آخر تحديث {date}",
	loadMore: "تحميل المزيد",
	message404: "عذرًا، تم الانتقال إلى صفحة 404.",
	navigateHome: "عُد إلى الصفحة الرئيسية.",
	new: "جديد",
	noActivities: "لا تتوفر أي أنشطة، أو سبق أن تم تسجيلك في الأنشطة كلها. حاول مرة أخرى في وقت لاحق.",
	noActivitiesExceptPrmoted: "لا تتوفر أي أنشطة جديدة أو محدّثة، أو سبق أن تم تسجيلك في الأنشطة كلها. حاول مرة أخرى في وقت لاحق.",
	noCourseDescription: "ما من وصف للمقرر التعليمي",
	noResultsHeading: "ما من نتائج لـ \"{searchQuery}\"",
	noResultsMessage: "حاول استخدام مصطلح بحث مختلف أو {linkStart}استعراض الكل{linkEnd} لعرض كل المواد المتوفرة",
	onMyList: "على لائحتي",
	openCourse: "فتح مقرر تعليمي",
	or: "أو",
	pageAllLoadedMessage: "تم تحميل صفحة المقررات التعليمية.",
	pageNext: "الانتقال إلى الصفحة التالية",
	pagePrevious: "الانتقال إلى الصفحة السابقة",
	pageSelection: "في الصفحة {pageCurrent} من أصل {pageTotal}. إدخال رقم صفحة للانتقال إليها",
	pageSelectionInvalid: "يجب أن تتراوح القيمة ما بين 1 و{pageTotal}",
	recentlyUpdatedAllLoadedMessage: "تم تحميل كل المقررات التعليمية التي تم تحديثها مؤخرًا",
	resultsFor: "{amount} من النتائج لـ \"{searchQuery}\"",
	search: "بحث",
	searchPlaceholder: "البحث...",
	searchKeywords: "البحث عن الكلمات الأساسية",
	searchPageDocumentTitle: "بحث: {searchTerm} - أداة الاكتشاف - {instanceName}",
	searchResultCount: "{searchResultRange} من أصل {searchResultsTotal} لـ \"{searchQuery}\"",
	searchResultCountForAllResults: "{searchResultRange} من أصل {searchResultsTotal} من النتائج",
	searchResultsOffscreen: "نتائج البحث لـ \"{searchQuery}\"",
	searchResultsReadyMessage: "أصبحت الصفحة {pageCurrent} من أصل {pageTotal} جاهزة الآن لـ \"{searchQuery}\"",
	searchResultsReadyMessageForAllResults: "أصبحت الصفحة {pageCurrent} من أصل {pageTotal} جاهزة الآن",
	settings: "الإعدادات",
	settingsLabel: "النقر لعرض صفحة الإعدادات",
	sorting_enrolled: "تم التسجيل مسبقًا",
	sorting_mostRelevant: "الأكثر صلة",
	sorting_new: "جديد",
	sorting_sortBy: "الفرز حسب",
	sorting_updated: "تم التحديث",
	startDate: "تاريخ البدء",
	startDateIsInTheFuture: "سيتوفر هذا المقرر التعليمي بتاريخ {date}.",
	startLearning: "بدء التعلم",
	unenroll: "إلغاء التسجيل",
	unenrollConfirmBody: "تم إلغاء تسجيلك بنجاح من \"{title}\".",
	unenrollConfirmHeader: "اكتمال إلغاء التسجيل",
	updated: "تم التحديث",
	viewAll: "عرض الكل",
	viewAllLabel: "النقر لعرض كل الأنشطة",
	viewAllNewLabel: "النقر لعرض الأنشطة الجديدة",
	viewAllUpdatedLabel: "النقر لعرض الأنشطة المحدّثة مؤخرًا",
	viewMyList: "عرض لائحتي",
	welcomeToTheCourse: "مرحبًا بك في المقرر التعليمي!"
};
