export default {
	OK : "Iawn",
	accessMaterials : "Mynd i’r Deunyddiau",
	addToMyList : "Ychwanegu at fy Rhestr",
	addedToMyLearningHeader : "Llwyddwyd i Ychwanegu at Fy Nysgu",
	addedToYourList : "Ychwanegwyd at eich rhestr",
	all : "Pob un",
	alreadyEnrolled : "Rydych eisoes wedi’ch cofrestru",
	backToDiscover : "Yn ôl i Darganfod",
	browseAllContent : "Pori’r holl gynnwys",
	close : "Cau",
	continueBrowsing : "Parhau i bori",
	courseCode : "Cod y Cwrs",
	courseDescription : "Disgrifiad o’r Cwrs",
	courseInfo : "Gwybodaeth am y Cwrs",
	coursePageDocumentTitle : "{courseName} - Darganfod - {instanceName}",
	courseSummaryReadyMessage : "Mae {courseTitle} bellach yn barod",
	discover : "Darganfod",
	discoverHomeMessage : "Dyma dudalen hafan Darganfod",
	discovery : "Darganfod",
	durationMinutes : "{minutes} o funudau",
	emailFeedback : "Anfon eich adborth i {email}",
	endDate : "Dyddiad dod i ben",
	endDateIsInThePast : "Mae’r cwrs hwn wedi cau ar {date}.",
	enrollInCourse : "Cofrestru ar Gwrs",
	enrollmentHeaderFail : "Methwyd â Chofrestru",
	enrollmentHeaderPending : "Cofrestru ar y Gweill",
	enrollmentHeaderSuccess : "Llwyddwyd i Gofrestru",
	enrollmentHeaderUnenrolled : "Dim Mynediad ar hyn o bryd",
	enrollmentMessageFail : "Doedd dim modd cofrestru ar hyn o bryd. Rhowch gynnig arall arni’n hwyrach.",
	enrollmentMessagePending : "Mae eich cofrestriad ar y cwrs hwn ar y gweill, dewch yn ôl cyn bo hir i gyrchu’r cwrs hwn.",
	enrollmentMessageSuccess : "Bydd {title} ar gael yn fuan yn y teclyn Fy Nghyrsiau.",
	enrollmentMessageSuccessFuture : "Bydd {title} yn dod ar gael yn y teclyn Fy Nghyrsiau ar {date}",
	enrollmentMessageSuccessPast : "Daeth {title} i ben ar {date}",
	enrollmentMessageUnenrolled : "Rydych chi wedi’ch dadgofrestru gan Weinyddwr, cysylltwch â'ch Gweinyddwr i ailgofrestru.",
	enrollmentOptions : "Dewisiadau Cofrestru",
	firstPublished : "Cyhoeddwyd yn gyntaf",
	homepageDocumentTitle : "Darganfod - {instanceName}",
	lastUpdatedDate : "Diweddarwyd diwethaf {date}",
	loadMore : "Llwytho Mwy",
	message404 : "O na! Rydych chi wedi dod ar draws 404.",
	navigateHome : "Mynd yn ôl i’r dudalen hafan.",
	new : "Newydd",
	noActivities : "Nid oes unrhyw weithgareddau ar gael neu rydych chi eisoes wedi cofrestru ar gyfer pob un ohonynt. Rhowch gynnig arall arni’n hwyrach.",
	noActivitiesExceptPrmoted : "Nid oes unrhyw weithgareddau newydd neu wedi’u diweddaru ar gael neu rydych chi eisoes wedi cofrestru ar gyfer pob un ohonynt. Rhowch gynnig arall arni’n hwyrach.",
	noCourseDescription : "Dim disgrifiad o’r cwrs",
	noResultsHeading : "Dim canlyniadau ar gyfer \"{searchQuery}\"",
	noResultsMessage : "Ceisiwch ddefnyddio term chwilio gwahanol neu {linkStart}Pori’r Cyfan{linkEnd} i weld yr holl ddeunyddiau sydd ar gael",
	onMyList : "Ar Fy Rhestr",
	openCourse : "Agor Cwrs",
	or : "neu",
	pageAllLoadedMessage : "Mae’r dudalen cyrsiau wedi cael ei llwytho.",
	pageNext : "I’r dudalen nesaf",
	pagePrevious : "I’r dudalen flaenorol",
	pageSelection : "Ar dudalen {pageCurrent} o {pageTotal}. Rhowch rif tudalen i fynd i’r dudalen honno",
	pageSelectionInvalid : "Rhaid i’r gwerth fod rhwng 1 a {pageTotal}",
	recentlyUpdatedAllLoadedMessage : "Mae pob cwrs sydd wedi cael ei ddiweddaru’n ddiweddar wedi llwytho",
	resultsFor : "{amount} o ganlyniadau ar gyfer \"{searchQuery}\"",
	search : "Chwilio",
	search_placeholder : "Chwilio…",
	searchKeywords : "Chwilio Geiriau Allweddol",
	searchPageDocumentTitle : "Chwilio: {searchTerm} - Darganfod - {instanceName}",
	searchResultCount : "{searchResultRange} o {searchResultsTotal} ar gyfer \"{searchQuery}\"",
	searchResultCountForAllResults : "{searchResultRange} o {searchResultsTotal} o ganlyniadau",
	searchResultsOffscreen : "Canlyniadau Chwilio ar gyfer \"{searchQuery}\"",
	searchResultsReadyMessage : "Mae tudalen {pageCurrent} o {pageTotal} ar gyfer \"{searchQuery}\" bellach yn barod",
	searchResultsReadyMessageForAllResults : "Mae tudalen {pageCurrent} o {pageTotal} bellach yn barod",
	settings : "Gosodiadau",
	settingsLabel : "Cliciwch i weld y dudalen gosodiadau",
	sorting_enrolled : "Wedi Cofrestru Eisoes",
	sorting_mostRelevant : "Mwyaf Perthnasol",
	sorting_new : "Newydd",
	sorting_sortBy : "Trefnu yn ôl",
	sorting_updated : "Wedi diweddaru",
	startDate : "Dyddiad Dechrau",
	startDateIsInTheFuture : "Bydd y cwrs hwn yn dod ar gael ar {date}.",
	startLearning : "Dechrau Dysgu",
	unenroll : "Dadgosfrestru",
	unenrollConfirmBody : "Rydych wedi llwyddo i ddatgofrestru o \"{title}\".",
	unenrollConfirmHeader : "Wedi datgofrestru",
	updated : "Wedi diweddaru",
	viewAll : "Gweld y Cyfan",
	viewAllLabel : "Cliciwch i weld pob gweithgaredd",
	viewAllNewLabel : "Cliciwch i weld gweithgareddau newydd",
	viewAllUpdatedLabel : "Cliciwch i weld gweithgareddau sydd wedi cael eu diweddaru’n ddiweddar",
	viewMyList : "Gweld fy rhestr",
	welcomeToTheCourse : "Croeso i’r cwrs!"
};
