export default {
	OK: "OK",
	accessMaterials: "Få adgang til materialer",
	addToMyList: "Føj til min liste",
	addedToMyLearningHeader: "Føjet til min undervisning",
	addedToYourList: "Føjet til din liste",
	all: "Alle",
	alreadyEnrolled: "Allerede tilmeldt",
	backToDiscover: "Tilbage til Registrer",
	browseAllContent: "Gennemse alt indhold",
	close: "Luk",
	continueBrowsing: "Fortsæt med at gennemse",
	courseCode: "Kursuskode",
	courseDescription: "Kursusbeskrivelse",
	courseInfo: "Kursusoplysninger",
	coursePageDocumentTitle: "{courseName} - Registrer - {instanceName}",
	courseSummaryReadyMessage: "{courseTitle} er nu klar",
	discover: "Registrer",
	discoverHomeMessage: "Dette er startsiden for Registrer.",
	discovery: "Registrering",
	durationMinutes: "{minutes} minutter",
	emailFeedback: "Send en e-mail med din feedback til {email}",
	endDate: "Slutdato",
	endDateIsInThePast: "Dette kursus lukkede den {date}.",
	enrollInCourse: "Tilmeld til kurset",
	enrollmentHeaderFail: "Kunne ikke tilmelde",
	enrollmentHeaderPending: "Tilmelding er udestående",
	enrollmentHeaderSuccess: "Tilmelding gennemført",
	enrollmentHeaderUnenrolled: "Ingen aktuel adgang",
	enrollmentMessageFail: "Tilmelding kunne ikke gennemføres på nuværende tidspunkt, prøv igen senere.",
	enrollmentMessagePending: "Din tilmelding til dette kursus er udestående. Kontroller snart igen for at få adgang til dette kursus.",
	enrollmentMessageSuccess: "{title} er snart tilgængelig i widgeten Mine kurser.",
	enrollmentMessageSuccessFuture: "{title} bliver tilgængeligt i widgeten Mine kurser d. {date}",
	enrollmentMessageSuccessPast: "{title} sluttede d. {date}",
	enrollmentMessageUnenrolled: "Du er blevet afmeldt af en administrator. Kontakt din administrator for at blive tilmeldt igen.",
	enrollmentOptions: "Tilmeldingsindstillinger",
	firstPublished: "Udgivet første gang",
	homepageDocumentTitle: "Registrer – {instanceName}",
	lastUpdatedDate: "Senest opdateret {date}",
	loadMore: "Indlæs flere",
	message404: "Hovsa, du aktiverede en 404.",
	navigateHome: "Gå tilbage til startsiden.",
	new: "Ny",
	noActivities: "Der er ingen aktiviteter tilgængelige, eller du er allerede tilmeldt dem alle. Prøv igen senere.",
	noActivitiesExceptPrmoted: "Der er ingen nye eller opdaterede aktiviteter tilgængelige, eller du er allerede tilmeldt dem alle. Prøv igen senere.",
	noCourseDescription: "Ingen kursusbeskrivelse",
	noResultsHeading: "Ingen resultater for \"{searchQuery}\"",
	noResultsMessage: "Prøv at bruge et andet søgeord eller {linkStart}Gennemse alle{linkEnd} for at få vist alt tilgængeligt materiale",
	onMyList: "På min liste",
	openCourse: "Åbn kursus",
	or: "eller",
	pageAllLoadedMessage: "Kursussiden er indlæst.",
	pageNext: "Til næste side",
	pagePrevious: "Til forrige side",
	pageSelection: "På side {pageCurrent} af {pageTotal}. Indtast et sidetal for at gå til denne side",
	pageSelectionInvalid: "Værdien skal ligge på mellem 1 og {pageTotal}",
	recentlyUpdatedAllLoadedMessage: "Alle nyligt opdaterede kurser er blevet indlæst",
	resultsFor: "{amount} resultater for \"{searchQuery}\"",
	search: "Søg",
	searchPlaceholder: "Søg ...",
	searchKeywords: "Søg efter nøgleord",
	searchPageDocumentTitle: "Søgning: {searchTerm} - Registrer - {instanceName}",
	searchResultCount: "{searchResultRange} af {searchResultsTotal} for \"{searchQuery}\"",
	searchResultCountForAllResults: "{searchResultRange} af {searchResultsTotal} resultater",
	searchResultsOffscreen: "Søgeresultater for \"{searchQuery}\"",
	searchResultsReadyMessage: "Side {pageCurrent} af {pageTotal} for \"{searchQuery}\" er klar",
	searchResultsReadyMessageForAllResults: "Side {pageCurrent} af {pageTotal} er klar",
	settings: "Indstillinger",
	settingsLabel: "Klik for at få vist siden med indstillinger",
	sorting_enrolled: "Allerede tilmeldt",
	sorting_mostRelevant: "Mest relevant",
	sorting_new: "Ny",
	sorting_sortBy: "Sortér efter",
	sorting_updated: "Opdateret",
	startDate: "Startdato",
	startDateIsInTheFuture: "Dette kursus bliver tilgængeligt den {date}.",
	startLearning: "Start undervisning",
	unenroll: "Afmeld",
	unenrollConfirmBody: "Du er blevet afmeldt fra \"{title}\".",
	unenrollConfirmHeader: "Afmelding fuldført",
	updated: "Opdateret",
	viewAll: "Vis alle",
	viewAllLabel: "Klik for at få vist alle aktiviteter",
	viewAllNewLabel: "Klik for at få vist nye aktiviteter",
	viewAllUpdatedLabel: "Klik for at få vist aktiviteter, der er opdateret for nylig",
	viewMyList: "Vis min liste",
	welcomeToTheCourse: "Velkommen til kurset!"
};
