export default {
	OK : "Aceptar",
	accessMaterials : "Acceder a materiales",
	addToMyList : "Agregar a mi lista",
	addedToMyLearningHeader : "Se ha agregado correctamente a Mi aprendizaje",
	addedToYourList : "Se ha agregado a su lista",
	all : "Todos",
	alreadyEnrolled : "Ya inscrito",
	backToDiscover : "Volver a Descubrir",
	browseAllContent : "Examinar todo el contenido",
	close : "Cerrar",
	continueBrowsing : "Seguir navegando",
	courseCode : "Código de curso",
	courseDescription : "Descripción del curso",
	courseInfo : "Información del curso",
	coursePageDocumentTitle : "{courseName} - Descubrir: {instanceName}",
	courseSummaryReadyMessage : "{courseTitle} ya está listo",
	discover : "Descubrir",
	discoverHomeMessage : "Esta es la página de inicio de Descubrir.",
	discovery : "Descubrimiento",
	durationMinutes : "{minutes} minutos",
	emailFeedback : "Envíe sus comentarios a {email}",
	endDate : "Fecha final",
	endDateIsInThePast : "Este curso se cerró el {date}.",
	enrollInCourse : "Inscribirse en el curso",
	enrollmentHeaderFail : "Se ha producido un error en la inscripción",
	enrollmentHeaderPending : "La inscripción está pendiente",
	enrollmentHeaderSuccess : "Se ha inscrito correctamente",
	enrollmentHeaderUnenrolled : "No hay acceso actual",
	enrollmentMessageFail : "No se puede inscribir en este momento; vuelva a intentarlo más tarde.",
	enrollmentMessagePending : "Su inscripción en este curso está pendiente. Vuelva a comprobarlo pronto para acceder a este curso.",
	enrollmentMessageSuccess : "{title} pronto estará disponible en el widget Mis cursos.",
	enrollmentMessageSuccessFuture : "{title} estará disponible en el widget Mis cursos el {date}",
	enrollmentMessageSuccessPast : "{title} finalizó el {date}",
	enrollmentMessageUnenrolled : "Un administrador ha anulado su inscripción. Póngase en contacto con su administrador para volver a inscribirse.",
	enrollmentOptions : "Opciones de inscripción",
	firstPublished : "Primera publicación",
	homepageDocumentTitle : "Descubrir: {instanceName}",
	lastUpdatedDate : "Última actualización {date}",
	loadMore : "Cargar más",
	message404 : "Lo sentimos. Se ha producido un 404.",
	navigateHome : "Regresar a la página de inicio.",
	new : "Nuevo",
	noActivities : "No hay ninguna actividad disponible o ya se ha inscrito en todas. Vuelva a intentarlo más tarde.",
	noActivitiesExceptPrmoted : "No hay ninguna actividad nueva o actualizada disponible o ya se ha inscrito en todas. Vuelva a intentarlo más tarde.",
	noCourseDescription : "Sin descripción del curso",
	noResultsHeading : "No hay resultados para \"{searchQuery}\"",
	noResultsMessage : "Intente utilizar un término de búsqueda distinto o {linkStart}Examinar todo{linkEnd} para ver todos los materiales disponibles",
	onMyList : "En mi lista",
	openCourse : "Abrir curso",
	or : "o",
	pageAllLoadedMessage : "Se ha cargado la página de cursos.",
	pageNext : "A la siguiente página",
	pagePrevious : "A la página anterior",
	pageSelection : "En la página {pageCurrent} de {pageTotal}. Introduzca un número de página para ir a esa página",
	pageSelectionInvalid : "El valor debe estar comprendido entre 1 y {pageTotal}",
	recentlyUpdatedAllLoadedMessage : "Se han cargado todos los cursos actualizados recientemente",
	resultsFor : "{amount} resultados para \"{searchQuery}\"",
	search : "Buscar",
	searchPlaceholder : "Buscar…",
	searchKeywords : "Buscar palabras clave",
	searchPageDocumentTitle : "Buscar: {searchTerm} - Descubrir: {instanceName}",
	searchResultCount : "{searchResultRange} de {searchResultsTotal} para \"{searchQuery}\"",
	searchResultCountForAllResults : "{searchResultRange} de {searchResultsTotal} resultados",
	searchResultsOffscreen : "Resultados de búsqueda para \"{searchQuery}\"",
	searchResultsReadyMessage : "La página {pageCurrent} de {pageTotal} para {searchQuery} ahora está lista",
	searchResultsReadyMessageForAllResults : "La página {pageCurrent} de {pageTotal} ahora está lista",
	settings : "Configuración",
	settingsLabel : "Haga clic para acceder a la página de ajustes",
	sorting_enrolled : "Ya está inscrito",
	sorting_mostRelevant : "Más relevante",
	sorting_new : "Nuevo",
	sorting_sortBy : "Ordenar por",
	sorting_updated : "Se ha actualizado",
	startDate : "Fecha de inicio",
	startDateIsInTheFuture : "Este curso estará disponible el {date}.",
	startLearning : "Iniciar aprendizaje",
	unenroll : "Cancelar inscripción",
	unenrollConfirmBody : "Se ha anulado correctamente la inscripción de \"{title}\".",
	unenrollConfirmHeader : "Anulación de inscripción completa",
	updated : "Se ha actualizado",
	viewAll : "Ver todo",
	viewAllLabel : "Haga clic para ver todas las actividades",
	viewAllNewLabel : "Haga clic para ver las actividades nuevas",
	viewAllUpdatedLabel : "Haga clic para ver las actividades actualizadas recientemente",
	viewMyList : "Ver mi lista",
	welcomeToTheCourse : "¡Bienvenido al curso!"
};
