export default {
	OK: "Aceptar",
	accessMaterials: "Acceder a materiales",
	addToMyList: "Agregar a mi lista",
	addedToMyLearningHeader: "Se agregó correctamente a Mi aprendizaje",
	addedToYourList: "Se agregó a su lista",
	all: "Todo",
	alreadyEnrolled: "Ya inscrito",
	backToDiscover: "Volver a Descubrir",
	browseAllContent: "Examinar todo el contenido",
	close: "Cerrar",
	continueBrowsing: "Seguir navegando",
	courseCode: "Código de curso",
	courseDescription: "Descripción del curso",
	courseInfo: "Información del curso",
	coursePageDocumentTitle: "{courseName} - Descubrir: {instanceName}",
	courseSummaryReadyMessage: "{courseTitle} ya está listo",
	discover: "Descubrir",
	discoverHomeMessage: "Esta es la página de inicio de Descubrir.",
	discovery: "Descubrimiento",
	durationMinutes: "{minutes} minutos",
	emailFeedback: "Envíe sus comentarios a {email}",
	endDate: "Fecha final",
	endDateIsInThePast: "Este curso se cerró el {date}.",
	enrollInCourse: "Inscribirse en el curso",
	enrollmentHeaderFail: "Se produjo un error al inscribir",
	enrollmentHeaderPending: "La inscripción está pendiente",
	enrollmentHeaderSuccess: "Se inscribió correctamente",
	enrollmentHeaderUnenrolled: "Sin acceso actualmente",
	enrollmentMessageFail: "No se puede inscribir en este momento, vuelva a intentarlo más tarde.",
	enrollmentMessagePending: "Su inscripción en el curso está pendiente, vuelva a verificar más tarde el acceso a este curso.",
	enrollmentMessageSuccess: "{title} pronto estará disponible en el componente Mis cursos.",
	enrollmentMessageSuccessFuture: "{title} estará disponible en el componente Mis cursos el {date}",
	enrollmentMessageSuccessPast: "{title} finalizó el {date}",
	enrollmentMessageUnenrolled: "Un administrador anuló su inscripción, comuníquese con el administrador para volver a inscribirse.",
	enrollmentOptions: "Opciones de inscripción",
	firstPublished: "Primera publicación",
	homepageDocumentTitle: "Descubrir: {instanceName}",
	lastUpdatedDate: "Última actualización {date}",
	loadMore: "Cargar más",
	message404: "Lo sentimos, obtuvo un 404.",
	navigateHome: "Regresar a la página de inicio.",
	new: "Nuevo",
	noActivities: "No hay actividades disponibles o ya está inscrito en todas ellas. Inténtelo de nuevo más tarde.",
	noActivitiesExceptPrmoted: "No hay actividades nuevas ni actualizadas disponibles o ya está inscrito en todas ellas. Inténtelo de nuevo más tarde.",
	noCourseDescription: "Sin descripción del curso",
	noResultsHeading: "No hay resultados para \"{searchQuery}\"",
	noResultsMessage: "Intente utilizar un término de búsqueda distinto o use {linkStart}Examinar todo{linkEnd} para ver todos los materiales disponibles",
	onMyList: "En mi lista",
	openCourse: "Abrir curso",
	or: "o",
	pageAllLoadedMessage: "Se cargó la página de cursos.",
	pageNext: "A la siguiente página",
	pagePrevious: "A la página anterior",
	pageSelection: "En la página {pageCurrent} de {pageTotal}. Ingrese un número de página para ir a ella",
	pageSelectionInvalid: "El valor debe estar comprendido entre 1 y {pageTotal}",
	recentlyUpdatedAllLoadedMessage: "Se cargaron todos los cursos actualizados recientemente",
	resultsFor: "{amount} resultados para \"{searchQuery}\"",
	search: "Buscar",
	searchPlaceholder: "Buscar…",
	searchKeywords: "Buscar palabras clave",
	searchPageDocumentTitle: "Buscar: {searchTerm} - Descubrir: {instanceName}",
	searchResultCount: "{searchResultRange} de {searchResultsTotal} para \"{searchQuery}\"",
	searchResultCountForAllResults: "{searchResultRange} de {searchResultsTotal} resultados",
	searchResultsOffscreen: "Resultados de búsqueda para \"{searchQuery}”",
	searchResultsReadyMessage: "La página {pageCurrent} de {pageTotal} para \"{searchQuery}\" ahora está lista",
	searchResultsReadyMessageForAllResults: "La página {pageCurrent} de {pageTotal} ahora está lista",
	settings: "Configuración",
	settingsLabel: "Haga clic para ver la página de configuración",
	sorting_enrolled: "Ya inscrito",
	sorting_mostRelevant: "Más relevante",
	sorting_new: "Nuevo",
	sorting_sortBy: "Ordenar por",
	sorting_updated: "Actualizado",
	startDate: "Fecha de inicio",
	startDateIsInTheFuture: "Este curso estará disponible el {date}.",
	startLearning: "Iniciar aprendizaje",
	unenroll: "Anular inscripción",
	unenrollConfirmBody: "Su inscripción a “{title}” se anuló correctamente.",
	unenrollConfirmHeader: "Anulación de inscripción completa",
	updated: "Actualizado",
	viewAll: "Ver todo",
	viewAllLabel: "Haga clic para ver todas las actividades",
	viewAllNewLabel: "Haga clic para ver nuevas actividades",
	viewAllUpdatedLabel: "Haga clic para ver actividades recién actualizadas",
	viewMyList: "Ver mi lista",
	welcomeToTheCourse: "¡Bienvenido al curso!"
};
