export default {
	OK: "OK",
	accessMaterials: "Accéder au matériel didactique",
	addToMyList: "Ajouter à ma liste",
	addedToMyLearningHeader: "Ajouté à mon environnement d’apprentissage",
	addedToYourList: "Ajouté à votre liste",
	all: "Tous",
	alreadyEnrolled: "Déjà inscrit",
	backToDiscover: "Retour à la section Discover (Découvrir)",
	browseAllContent: "Parcourir tout le contenu",
	close: "Fermer",
	continueBrowsing: "Poursuivre la navigation",
	courseCode: "Code de cours",
	courseDescription: "Description du cours",
	courseInfo: "Informations sur le cours",
	coursePageDocumentTitle: "{courseName} - Discover (Découvrir)- {instanceName}",
	courseSummaryReadyMessage: "Le cours {courseTitle} est maintenant prêt",
	discover: "Discover (Découvrir)",
	discoverHomeMessage: "Voici la page d’accueil de la section Discover (Découvrir)",
	discovery: "Découverte",
	durationMinutes: "{minutes} minutes",
	emailFeedback: "Envoyez vos réactions par e-mail à {email}",
	endDate: "Date de fin",
	endDateIsInThePast: "Ce cours a été clôturé le {date}.",
	enrollInCourse: "Inscription au cours",
	enrollmentHeaderFail: "Échec de l’inscription",
	enrollmentHeaderPending: "Inscription en attente",
	enrollmentHeaderSuccess: "Inscription réussie",
	enrollmentHeaderUnenrolled: "Aucun accès pour l’instant",
	enrollmentMessageFail: "Inscription impossible pour le moment, réessayez ultérieurement.",
	enrollmentMessagePending: "Votre inscription à ce cours est toujours en attente.",
	enrollmentMessageSuccess: "{title} sera bientôt disponible dans le widget My Courses (Mes cours).",
	enrollmentMessageSuccessFuture: "{title} sera disponible dans le widget My Courses (Mes cours) le {date}",
	enrollmentMessageSuccessPast: "{title} s’est terminé le {date}",
	enrollmentMessageUnenrolled: "Vous avez été désinscrit par un administrateur, contactez votre administrateur pour vous inscrire à nouveau.",
	enrollmentOptions: "Options d’inscription",
	firstPublished: "Première publication",
	homepageDocumentTitle: "Discover (Découvrir) - {instanceName}",
	lastUpdatedDate: "Dernière mise à jour le {date}",
	loadMore: "Charger plus",
	message404: "Erreur 404.",
	navigateHome: "Revenir à la page d’accueil.",
	new: "Nouvelle",
	noActivities: "Aucune activité disponible ou vous êtes déjà inscrit à toutes les activités. Réessayez ultérieurement.",
	noActivitiesExceptPrmoted: "Il n’y a pas d’activité nouvelle ou mise à jour ou vous êtes déjà inscrit à toutes les activités. Réessayez ultérieurement.",
	noCourseDescription: "Aucune description de cours",
	noResultsHeading: "Aucun résultat pour « {searchQuery} »",
	noResultsMessage: "Essayez d’utiliser un autre terme de recherche ou {linkStart}Tout parcourir{linkEnd} pour afficher tout le matériel disponible",
	onMyList: "Dans ma liste",
	openCourse: "Ouvrir le cours",
	or: "ou",
	pageAllLoadedMessage: "La page des cours a été chargée.",
	pageNext: "Accéder à la page suivante",
	pagePrevious: "Accéder à la page précédente",
	pageSelection: "Page {pageCurrent} sur {pageTotal}. Saisissez un numéro de page pour accéder à cette page",
	pageSelectionInvalid: "La valeur doit être comprise entre 1 et {pageTotal}",
	recentlyUpdatedAllLoadedMessage: "Tous les cours récemment mis à jour ont été chargés",
	resultsFor: "{amount} résultats pour « {searchQuery} »",
	search: "Rechercher",
	searchPlaceholder: "Rechercher...",
	searchKeywords: "Rechercher des mots-clés",
	searchPageDocumentTitle: "Recherche : {searchterm} - Discover (Découvrir) - {instanceName}",
	searchResultCount: "{searchResultRange} sur {searchResultsTotal} pour « {searchQuery} »",
	searchResultCountForAllResults: "{searchResultRange} résultats sur {searchResultsTotal}",
	searchResultsOffscreen: "Résultats de la recherche pour « {searchQuery} »",
	searchResultsReadyMessage: "La page {pageCurrent} sur {pageTotal} pour « {searchQuery} » est maintenant prête",
	searchResultsReadyMessageForAllResults: "La page {pageCurrent} sur {pageTotal} est maintenant prête",
	settings: "Paramètres",
	settingsLabel: "Cliquez pour afficher la page des paramètres",
	sorting_enrolled: "Déjà inscrit",
	sorting_mostRelevant: "Les plus pertinents",
	sorting_new: "Nouvelle",
	sorting_sortBy: "Trier par",
	sorting_updated: "Mis à jour",
	startDate: "Date de début",
	startDateIsInTheFuture: "Ce cours sera disponible le {date}.",
	startLearning: "Commencer l’apprentissage",
	unenroll: "Désinscription",
	unenrollConfirmBody: "Vous avez été désinscrit de « {title} ».",
	unenrollConfirmHeader: "Désinscription terminée",
	updated: "Mis à jour",
	viewAll: "Tout afficher",
	viewAllLabel: "Cliquer pour afficher toutes les activités",
	viewAllNewLabel: "Cliquer pour afficher toutes les nouvelles activités",
	viewAllUpdatedLabel: "Cliquer pour afficher les activités récemment mises à jour",
	viewMyList: "Afficher ma liste",
	welcomeToTheCourse: "Bienvenue dans le cours !"
};
