export default {
	OK: "OK",
	accessMaterials: "Accéder au matériel",
	addToMyList: "Ajouter à ma liste",
	addedToMyLearningHeader: "Ajouté avec succès à Mes apprentissages",
	addedToYourList: "Ajouté à votre liste",
	all: "Tous",
	alreadyEnrolled: "Déjà inscrit",
	backToDiscover: "Retour à Découvrir",
	browseAllContent: "Parcourir tout le contenu",
	close: "Fermer",
	continueBrowsing: "Poursuivre la navigation",
	courseCode: "Code de cours",
	courseDescription: "Description du cours",
	courseInfo: "Renseignements du cours",
	coursePageDocumentTitle: "{courseName} – Découvrir – {instanceName}",
	courseSummaryReadyMessage: "Le cours {courseTitle} est maintenant prêt",
	discover: "Découvrir",
	discoverHomeMessage: "Vous êtes sur la page d'accueil de l'outil Découvrir.",
	discovery: "Découvrir",
	durationMinutes: "{minutes} minutes",
	emailFeedback: "Envoyez vos commentaires par courriel à l'adresse {email}",
	endDate: "Date de fin",
	endDateIsInThePast: "Ce cours est terminé depuis le {date}.",
	enrollInCourse: "S'inscrire au cours",
	enrollmentHeaderFail: "Échec de l'inscription",
	enrollmentHeaderPending: "L'inscription est en attente",
	enrollmentHeaderSuccess: "Inscription effectuée avec succès",
	enrollmentHeaderUnenrolled: "Aucun accès actuellement",
	enrollmentMessageFail: "Impossible de vous inscrire en ce moment, veuillez réessayer plus tard.",
	enrollmentMessagePending: "Votre inscription à ce cours est en attente, revenez bientôt pour accéder à ce cours.",
	enrollmentMessageSuccess: "{title} sera bientôt disponible dans le composant graphique Mes cours.",
	enrollmentMessageSuccessFuture: "{title} sera disponible dans le composant graphique Mes cours le {date}",
	enrollmentMessageSuccessPast: "{title} s'est terminé le {date}",
	enrollmentMessageUnenrolled: "Un administrateur a annulé votre inscription, communiquez avec votre administrateur pour vous inscrire à nouveau.",
	enrollmentOptions: "Options d'inscription",
	firstPublished: "Première publication",
	homepageDocumentTitle: "Découvrir – {instanceName}",
	lastUpdatedDate: "Dernière mise à jour effectuée le {date}",
	loadMore: "En voir plus",
	message404: "Oups, une erreur 404 de page introuvable est survenue.",
	navigateHome: "Revenir à la page d'accueil.",
	new: "Nouvelle",
	noActivities: "Aucune activité disponible ou vous êtes déjà inscrit(e) dans chacune d'elles. Réessayez plus tard.",
	noActivitiesExceptPrmoted: "Aucune activité nouvelle ou mise à jour n’est disponible, ou vous êtes déjà inscrit(e) à toutes les activités. Réessayez plus tard.",
	noCourseDescription: "Aucune description du cours",
	noResultsHeading: "Aucun résultat pour « {searchQuery} »",
	noResultsMessage: "Essayer un terme de recherche différent ou {linkStart}parcourez tout{linkEnd} pour voir tout le matériel disponible",
	onMyList: "Sur ma liste",
	openCourse: "Ouvrir le cours",
	or: "ou",
	pageAllLoadedMessage: "La page de cours a été chargée.",
	pageNext: "À la page suivante",
	pagePrevious: "À la page précédente",
	pageSelection: "À la page {pageCurrent} de {pageTotal}. Inscrivez un numéro de page pour accéder à celle-ci",
	pageSelectionInvalid: "La valeur doit être comprise entre 1 et {pageTotal}",
	recentlyUpdatedAllLoadedMessage: "Tous les cours récemment mis à jour ont été chargés",
	resultsFor: "{amount} résultats pour « {searchQuery} »",
	search: "Rechercher",
	searchPlaceholder: "Rechercher…",
	searchKeywords: "Rechercher les mots clés",
	searchPageDocumentTitle: "Rechercher : {searchTerm} – Découvrir – {instanceName}",
	searchResultCount: "{searchResultRange} de {searchResultsTotal} pour « {searchQuery} »",
	searchResultCountForAllResults: "{searchResultRange} de {searchResultsTotal} résultats",
	searchResultsOffscreen: "Résultats de recherche pour « {searchQuery} »",
	searchResultsReadyMessage: "Page {pageCurrent} de {pageTotal} pour « {searchQuery} » est maintenant prête",
	searchResultsReadyMessageForAllResults: "Page {pageCurrent} de {pageTotal} est maintenant prête",
	settings: "Réglages",
	settingsLabel: "Cliquez pour afficher la page des réglages",
	sorting_enrolled: "Déjà inscrit",
	sorting_mostRelevant: "Le plus pertinent",
	sorting_new: "Nouvelle",
	sorting_sortBy: "Trier par",
	sorting_updated: "Mis à jour",
	startDate: "Date de début",
	startDateIsInTheFuture: "Ce cours sera disponible à compter du {date}.",
	startLearning: "Débuter l'apprentissage",
	unenroll: "Se désinscrire",
	unenrollConfirmBody: "Vous avez été désinscrit(e) de « {title} ».",
	unenrollConfirmHeader: "Désinscription effectuée",
	updated: "Mis à jour",
	viewAll: "Tout afficher",
	viewAllLabel: "Cliquer pour afficher toutes les activités",
	viewAllNewLabel: "Cliquer pour afficher les nouvelles activités",
	viewAllUpdatedLabel: "Cliquer pour afficher les activités nouvellement mises à jour",
	viewMyList: "Afficher ma liste",
	welcomeToTheCourse: "Bienvenue au cours!"
};
