export default {
	OK: "OK",
	accessMaterials: "資料へのアクセス",
	addToMyList: "マイリストに追加",
	addedToMyLearningHeader: "マイラーニングに正常に追加されました",
	addedToYourList: "リストに追加されました",
	all: "すべて",
	alreadyEnrolled: "すでに登録済み",
	backToDiscover: "Discover に戻る",
	browseAllContent: "すべてのコンテンツの参照",
	close: "閉じる",
	continueBrowsing: "参照の続行",
	courseCode: "コースコード",
	courseDescription: "コースの説明",
	courseInfo: "コース情報",
	coursePageDocumentTitle: "{courseName} - Discover - {instanceName}",
	courseSummaryReadyMessage: "{courseTitle} の準備ができました",
	discover: "Discover",
	discoverHomeMessage: "Discover のホームページです。",
	discovery: "検出",
	durationMinutes: "{minutes} 分",
	emailFeedback: "{email} にフィードバックをメールする",
	endDate: "終了日",
	endDateIsInThePast: "このコースは {date} に終了しました。",
	enrollInCourse: "コースへの登録",
	enrollmentHeaderFail: "登録できませんでした",
	enrollmentHeaderPending: "登録は承認待ちです",
	enrollmentHeaderSuccess: "登録が完了しました",
	enrollmentHeaderUnenrolled: "現在、アクセス権がありません",
	enrollmentMessageFail: "現時点では登録できません。後でもう一度試してください。",
	enrollmentMessagePending: "このコースへの登録は承認待ちとなっています。このコースへのアクセスに関しては、のちほどご確認ください。",
	enrollmentMessageSuccess: "{title} はまもなくマイコースウィジェットに表示されます。",
	enrollmentMessageSuccessFuture: "{title} は {date} にマイコースウィジェットで使用可能です",
	enrollmentMessageSuccessPast: "{title} は {date} に終了しました",
	enrollmentMessageUnenrolled: "管理者が登録解除しました。管理者に連絡して再登録を依頼してください。",
	enrollmentOptions: "登録オプション",
	firstPublished: "初回公開日",
	homepageDocumentTitle: "Discover - {instanceName}",
	lastUpdatedDate: "最終更新日 {date}",
	loadMore: "さらに読み込む",
	message404: "404 エラーが発生しました。",
	navigateHome: "ホームに戻ります。",
	new: "新規",
	noActivities: "使用可能なアクティビティがないか、すべてのアクティビティにすでに登録済みです。後でもう一度試してください。",
	noActivitiesExceptPrmoted: "使用可能な新規または更新済みのアクティビティがないか、すべてのアクティビティにすでに登録済みです。後でもう一度試してください。",
	noCourseDescription: "コースの説明がありません",
	noResultsHeading: "「{searchQuery}」の検索結果はありません",
	noResultsMessage: "別の語句で検索するか、{linkStart}すべてを参照{linkEnd}して使用可能なすべての資料を表示してください",
	onMyList: "マイリスト",
	openCourse: "コースを開く",
	or: "または",
	pageAllLoadedMessage: "コースのページが読み込まれました。",
	pageNext: "次のページへ",
	pagePrevious: "前のページへ",
	pageSelection: "{pageTotal} ページ中 {pageCurrent} ページ目ページ番号を入力して、そのページに移動",
	pageSelectionInvalid: "値は 1～{pageTotal} のいずれかである必要があります",
	recentlyUpdatedAllLoadedMessage: "最近更新されたすべてのコースが読み込まれました",
	resultsFor: "\"{searchQuery}\" の結果 {amount} 件",
	search: "検索",
	searchPlaceholder: "検索...",
	searchKeywords: "検索キーワード",
	searchPageDocumentTitle: "検索: {searchTerm} - Discover - {instanceName}",
	searchResultCount: "「{searchQuery}」の結果 {searchResultsTotal} 件中 {searchResultRange} 件",
	searchResultCountForAllResults: "{searchResultsTotal} 件中 {searchResultRange} 件の結果",
	searchResultsOffscreen: "「{searchQuery}」の検索結果",
	searchResultsReadyMessage: "「{searchQuery}」に対して {pageTotal} ページ中 {pageCurrent} ページ目の準備ができました",
	searchResultsReadyMessageForAllResults: "{pageTotal} ページ中 {pageCurrent} ページ目の準備ができました",
	settings: "設定",
	settingsLabel: "クリックして設定ページを表示",
	sorting_enrolled: "登録済み",
	sorting_mostRelevant: "関連性が最も高い",
	sorting_new: "新規",
	sorting_sortBy: "並べ替え基準",
	sorting_updated: "更新済み",
	startDate: "開始日",
	startDateIsInTheFuture: "このコースは {date} に公開されます。",
	startLearning: "学習の開始",
	unenroll: "登録解除",
	unenrollConfirmBody: "「{title}」から正常に登録解除されました。",
	unenrollConfirmHeader: "登録解除完了",
	updated: "更新済み",
	viewAll: "すべてを表示",
	viewAllLabel: "クリックしてすべてのアクティビティを表示",
	viewAllNewLabel: "クリックして新規アクティビティを表示",
	viewAllUpdatedLabel: "クリックして新しく更新されたアクティビティを表示",
	viewMyList: "マイリストの表示",
	welcomeToTheCourse: "コースへようこそ。"
};
