export default {
	OK: "확인",
	accessMaterials: "자료 접근",
	addToMyList: "내 목록에 추가",
	addedToMyLearningHeader: "내 학습에 성공적으로 추가됨",
	addedToYourList: "귀하 목록에 추가됨",
	all: "모두",
	alreadyEnrolled: "이미 등록됨",
	backToDiscover: "Discover로 돌아가기",
	browseAllContent: "모든 콘텐츠 찾아보기",
	close: "닫기",
	continueBrowsing: "발견 계속",
	courseCode: "강의 코드",
	courseDescription: "강의 설명",
	courseInfo: "강의 정보",
	coursePageDocumentTitle: "{courseName} - 검색 - {instanceName}",
	courseSummaryReadyMessage: "{courseTitle}이(가) 준비되었습니다.",
	discover: "검색",
	discoverHomeMessage: "Discover 홈페이지입니다.",
	discovery: "발견",
	durationMinutes: "{minutes}분",
	emailFeedback: "{email}에 이메일로 피드백 보내기",
	endDate: "종료일",
	endDateIsInThePast: "이 강의는 {date}에 닫혔습니다.",
	enrollInCourse: "강의에 등록",
	enrollmentHeaderFail: "등록 실패",
	enrollmentHeaderPending: "등록 대기 중",
	enrollmentHeaderSuccess: "성공적으로 등록됨",
	enrollmentHeaderUnenrolled: "현재 접속 사항 없음",
	enrollmentMessageFail: "지금은 등록할 수 없습니다. 나중에 다시 시도하십시오.",
	enrollmentMessagePending: "본 강의에 대한 귀하의 등록이 대기 중입니다. 본 강의에 접근하려면 잠시 후 다시 확인하십시오.",
	enrollmentMessageSuccess: "{title}을(를) 곧 내 강의 위젯에서 사용할 수 있습니다.",
	enrollmentMessageSuccessFuture: "{date}에 {title}을(를) 내 강의 위젯에서 사용할 수 있습니다.",
	enrollmentMessageSuccessPast: "{date}에 {title} 종료됨",
	enrollmentMessageUnenrolled: "관리자가 귀하의 등록을 취소했습니다. 다시 등록하려면 관리자에게 문의하십시오.",
	enrollmentOptions: "등록 옵션",
	firstPublished: "처음 게시됨",
	homepageDocumentTitle: "검색 - {instanceName}",
	lastUpdatedDate: "마지막 업데이트 날짜: {date}",
	loadMore: "더 많이 로드",
	message404: "404를 기록했습니다.",
	navigateHome: "홈으로 돌아갑니다.",
	new: "신규",
	noActivities: "사용 가능한 활동이 없거나 이미 모든 활동에 등록되어 있습니다. 나중에 다시 시도하십시오.",
	noActivitiesExceptPrmoted: "새로운 또는 업데이트된 활동이 없거나 이미 모든 활동에 등록되어 있습니다. 나중에 다시 시도하십시오.",
	noCourseDescription: "강의 설명 없음",
	noResultsHeading: "\"{searchQuery}\"에 대한 결과 없음",
	noResultsMessage: "사용 가능한 모든 자료를 살펴보려면 다른 검색어 또는 {linkStart}모두 찾아보기{linkEnd}를 사용해 보십시오.",
	onMyList: "내 목록",
	openCourse: "강의 열기",
	or: "또는",
	pageAllLoadedMessage: "강의 페이지가 로드되었습니다.",
	pageNext: "다음 페이지로 이동",
	pagePrevious: "이전 페이지로 이동",
	pageSelection: "{pageCurrent} / {pageTotal} 페이지. 해당 페이지로 이동하려면 페이지 번호를 입력하십시오.",
	pageSelectionInvalid: "값은 1에서 {pageTotal} 사이여야 합니다.",
	recentlyUpdatedAllLoadedMessage: "최근에 업데이트된 모든 강의가 로드되었습니다.",
	resultsFor: "\"{searchQuery}\"에 대한 {amount} 결과",
	search: "검색",
	searchPlaceholder: "검색...",
	searchKeywords: "키워드 검색",
	searchPageDocumentTitle: "검색: {searchTerm} - 검색 - {instanceName}",
	searchResultCount: "\"{searchQuery}\"에 대한 {searchResultRange} / {searchResultsTotal}",
	searchResultCountForAllResults: "{searchResultRange}/{searchResultsTotal}개 결과",
	searchResultsOffscreen: "\"{searchQuery}\"에 대한 결과 검색",
	searchResultsReadyMessage: "\"{searchQuery}\"에 대한 {pageCurrent}/{pageTotal}페이지 준비되었음",
	searchResultsReadyMessageForAllResults: "{pageCurrent}/{pageTotal}페이지 준비되었음",
	settings: "설정",
	settingsLabel: "클릭하여 설정 페이지 보기",
	sorting_enrolled: "이미 등록됨",
	sorting_mostRelevant: "가장 높은 관련성",
	sorting_new: "신규",
	sorting_sortBy: "정렬 기준",
	sorting_updated: "업데이트됨",
	startDate: "시작일",
	startDateIsInTheFuture: "이 강좌는 {date}에 사용 가능합니다.",
	startLearning: "학습 시작",
	unenroll: "등록 취소",
	unenrollConfirmBody: "“{title}”에서 성공적으로 등록이 취소되었습니다.",
	unenrollConfirmHeader: "등록 취소 완료",
	updated: "업데이트됨",
	viewAll: "모두 보기",
	viewAllLabel: "클릭하여 모든 활동 보기",
	viewAllNewLabel: "클릭하여 새 활동 보기",
	viewAllUpdatedLabel: "클릭하여 새로 업데이트된 활동 보기",
	viewMyList: "내 목록 보기",
	welcomeToTheCourse: "강의에 오신 것을 환영합니다."
};
