export default {
	OK: "OK",
	accessMaterials: "Toegang tot materialen",
	addToMyList: "Toevoegen aan mijn lijst",
	addedToMyLearningHeader: "Toegevoegd aan Mijn leerproces",
	addedToYourList: "Toegevoegd aan uw lijst",
	all: "Alle",
	alreadyEnrolled: "Al ingeschreven",
	backToDiscover: "Terug naar Ontdekken",
	browseAllContent: "Door alle inhoud bladeren",
	close: "Sluiten",
	continueBrowsing: "Doorgaan met bladeren",
	courseCode: "Cursuscode",
	courseDescription: "Cursusbeschrijving",
	courseInfo: "Cursusinformatie",
	coursePageDocumentTitle: "{courseName} - Ontdekken - {instanceName}",
	courseSummaryReadyMessage: "{courseTitle} is nu gereed",
	discover: "Ontdekken",
	discoverHomeMessage: "Dit is de startpagina van Ontdekken.",
	discovery: "Discovery",
	durationMinutes: "{minutes} minuten",
	emailFeedback: "Stuur uw feedback per e-mail naar {email}",
	endDate: "Einddatum",
	endDateIsInThePast: "Deze cursus wordt gesloten op {date}.",
	enrollInCourse: "Inschrijven voor cursus",
	enrollmentHeaderFail: "Inschrijving mislukt",
	enrollmentHeaderPending: "Inschrijving in behandeling",
	enrollmentHeaderSuccess: "Inschrijving voltooid",
	enrollmentHeaderUnenrolled: "Momenteel geen toegang",
	enrollmentMessageFail: "Inschrijven is momenteel niet mogelijk. Probeer het later opnieuw.",
	enrollmentMessagePending: "Uw inschrijving voor deze cursus is in behandeling. Kom snel terug om met deze cursus te beginnen.",
	enrollmentMessageSuccess: "{title} is binnenkort beschikbaar in de widget Mijn cursussen.",
	enrollmentMessageSuccessFuture: "{title} is op {date} beschikbaar in de widget Mijn cursussen",
	enrollmentMessageSuccessPast: "{title} is beëindigd op {date}",
	enrollmentMessageUnenrolled: "U bent uitgeschreven door een beheerder. Neem contact op met uw beheerder om u opnieuw in te schrijven.",
	enrollmentOptions: "Inschrijvingsopties",
	firstPublished: "Eerste publicatie",
	homepageDocumentTitle: "Ontdekken - {instanceName}",
	lastUpdatedDate: "Laatst bijgewerkt op {date}",
	loadMore: "Meer laden",
	message404: "Oeps, u kreeg een 404-melding.",
	navigateHome: "Ga terug naar de startpagina.",
	new: "Nieuw",
	noActivities: "Er zijn geen activiteiten beschikbaar of u hebt u al voor alle activiteiten ingeschreven. Probeer het later opnieuw.",
	noActivitiesExceptPrmoted: "Er zijn geen nieuwe of bijgewerkte activiteiten beschikbaar of u hebt u al voor alle activiteiten ingeschreven. Probeer het later opnieuw.",
	noCourseDescription: "Geen cursusbeschrijving",
	noResultsHeading: "Geen resultaten voor '{searchQuery}'",
	noResultsMessage: "Probeer een andere zoekterm of {linkStart}Blader door alle inhoud{linkEnd} om alle beschikbare materialen te bekijken",
	onMyList: "Op mijn lijst",
	openCourse: "Cursus openen",
	or: "of",
	pageAllLoadedMessage: "De pagina met cursussen is geladen.",
	pageNext: "Naar volgende pagina",
	pagePrevious: "Naar vorige pagina",
	pageSelection: "Op pagina {pageCurrent} van {pageTotal}. Voer een paginanummer in om naar die pagina te gaan",
	pageSelectionInvalid: "Waarde moet tussen 1 en {pageTotal} liggen",
	recentlyUpdatedAllLoadedMessage: "Alle recent bijgewerkte cursussen zijn geladen",
	resultsFor: "{amount} resultaten voor '{searchQuery}'",
	search: "Zoeken",
	searchPlaceholder: "Zoeken...",
	searchKeywords: "Trefwoorden zoeken",
	searchPageDocumentTitle: "Zoeken: {searchTerm} - Ontdekken - {instanceName}",
	searchResultCount: "{searchResultRange} van {searchResultsTotal} voor '{searchQuery}'",
	searchResultCountForAllResults: "{searchResultRange} van {searchResultsTotal} resultaten",
	searchResultsOffscreen: "Resultaten zoeken voor '{searchQuery}'",
	searchResultsReadyMessage: "Pagina {pageCurrent} van {pageTotal} voor '{searchQuery}' is nu gereed",
	searchResultsReadyMessageForAllResults: "Pagina {pageCurrent} van {pageTotal} is nu gereed",
	settings: "Instellingen",
	settingsLabel: "Klik om de instellingenpagina te bekijken",
	sorting_enrolled: "Al ingeschreven",
	sorting_mostRelevant: "Meest relevant",
	sorting_new: "Nieuw",
	sorting_sortBy: "Sorteren op",
	sorting_updated: "Bijgewerkt",
	startDate: "Startdatum",
	startDateIsInTheFuture: "Deze cursus is beschikbaar vanaf {date}.",
	startLearning: "Cursus beginnen",
	unenroll: "Uitschrijven",
	unenrollConfirmBody: "U bent uitgeschreven bij '{title}'.",
	unenrollConfirmHeader: "Uitschrijving voltooid",
	updated: "Bijgewerkt",
	viewAll: "Alles weergeven",
	viewAllLabel: "Klik om alle activiteiten te bekijken",
	viewAllNewLabel: "Klik om nieuwe activiteiten te bekijken",
	viewAllUpdatedLabel: "Klik om onlangs bijgewerkte activiteiten te bekijken",
	viewMyList: "Mijn lijst weergeven",
	welcomeToTheCourse: "Welkom bij de cursus."
};
