export default {
	OK: "OK",
	accessMaterials: "Materiais de acesso",
	addToMyList: "Adicionar à minha lista",
	addedToMyLearningHeader: "Adicionado com êxito à Minha aprendizagem",
	addedToYourList: "Adicionado à sua lista",
	all: "Todas",
	alreadyEnrolled: "Já inscrito",
	backToDiscover: "Voltar ao Descubra",
	browseAllContent: "Procurar todo o conteúdo",
	close: "Fechar",
	continueBrowsing: "Continuar procurando",
	courseCode: "Código do Curso",
	courseDescription: "Descrição do Curso",
	courseInfo: "Informações do curso",
	coursePageDocumentTitle: "{courseName} – Discover – {instanceName}",
	courseSummaryReadyMessage: "{CourseTitle} está pronto",
	discover: "Discover",
	discoverHomeMessage: "Esta é a página inicial do Descubra.",
	discovery: "Descoberta",
	durationMinutes: "{minutes} minutos",
	emailFeedback: "Envie seu comentário por e-mail para {email}",
	endDate: "Data Final",
	endDateIsInThePast: "Este curso foi fechado em {date}.",
	enrollInCourse: "Inscrever-se no curso",
	enrollmentHeaderFail: "Falha na inscrição",
	enrollmentHeaderPending: "A inscrição está pendente",
	enrollmentHeaderSuccess: "Inscrito com êxito",
	enrollmentHeaderUnenrolled: "Sem acesso atual",
	enrollmentMessageFail: "Não foi possível se inscrever no momento, por favor, tente novamente mais tarde.",
	enrollmentMessagePending: "Sua inscrição neste curso está pendente. Verifique novamente em breve para acessar este curso.",
	enrollmentMessageSuccess: "{title} estará disponível em breve no widget Meus cursos.",
	enrollmentMessageSuccessFuture: "{title} estará disponível no widget Meus cursos em {date}",
	enrollmentMessageSuccessPast: "{title} terminou em {date}",
	enrollmentMessageUnenrolled: "Você foi inscrito novamente por um Administrador. Entre em contato com o Administrador para se inscrever novamente.",
	enrollmentOptions: "Opções de Inscrição",
	firstPublished: "Primeira publicação",
	homepageDocumentTitle: "Discover - {instanceName}",
	lastUpdatedDate: "Última atualização {date}",
	loadMore: "Carregar Mais",
	message404: "Opa, ocorreu um erro 404.",
	navigateHome: "Volte ao início.",
	new: "Novas",
	noActivities: "Não há atividades disponíveis, ou você já se inscreveu em todas elas. Tente novamente mais tarde.",
	noActivitiesExceptPrmoted: "Não há atividades novas ou atualizadas disponíveis ou você já se inscreveu em todas elas. Tente novamente mais tarde.",
	noCourseDescription: "Não há descrição do curso",
	noResultsHeading: "Nenhum resultado para \"{searchQuery}\"",
	noResultsMessage: "Use um termo de pesquisa diferente, ou clique em {linkStart}Procurar Tudo{linkEnd} para visualizar todos os materiais disponíveis",
	onMyList: "Em minha lista",
	openCourse: "Abra o curso",
	or: "ou",
	pageAllLoadedMessage: "A página de cursos foi carregada.",
	pageNext: "Para a próxima página",
	pagePrevious: "Para a página anterior",
	pageSelection: "Na página {pageCurrent} de {pageTotal}. Insira o número de uma página para acessá-la",
	pageSelectionInvalid: "O valor deve estar entre 1 e {pageTotal}",
	recentlyUpdatedAllLoadedMessage: "Todos os cursos atualizados recentemente foram carregados",
	resultsFor: "{amount} resultados para \"{searchQuery}\"",
	search: "Pesquisar",
	searchPlaceholder: "Pesquisar...",
	searchKeywords: "Pesquisar palavras-chave",
	searchPageDocumentTitle: "Pesquise: {searchTerm} - Discover - {instanceName}",
	searchResultCount: "{searchResultRange} de {searchResultsTotal} para \"{searchQuery}\"",
	searchResultCountForAllResults: "{searchResultRange} de {searchResultsTotal} resultados",
	searchResultsOffscreen: "Resultados da Pesquisa para \"{searchQuery}\"",
	searchResultsReadyMessage: "A página {pageCurrent} de {pageTotal} para \"{searchQuery}\" está pronta",
	searchResultsReadyMessageForAllResults: "A página {pageCurrent} de {pageTotal} está pronta",
	settings: "Configurações",
	settingsLabel: "Clique aqui para visualizar a página de configurações",
	sorting_enrolled: "Já inscrito",
	sorting_mostRelevant: "Mais relevante",
	sorting_new: "Novas",
	sorting_sortBy: "Classificar por",
	sorting_updated: "Atualizadas",
	startDate: "Data de Início",
	startDateIsInTheFuture: "Este curso estará disponível em {date}.",
	startLearning: "Iniciar aprendizagem",
	unenroll: "Cancelar Inscrição",
	unenrollConfirmBody: "Sua inscrição em \"{title}\" foi cancelada com êxito.",
	unenrollConfirmHeader: "Cancelamento de inscrição concluído",
	updated: "Atualizadas",
	viewAll: "Exibir Todas",
	viewAllLabel: "Clique aqui para visualizar todas as atividades",
	viewAllNewLabel: "Clique aqui para visualizar atividades novas",
	viewAllUpdatedLabel: "Clique aqui para visualizar atividades recém-atualizadas",
	viewMyList: "Exibir minha lista",
	welcomeToTheCourse: "Bem-vindo(a) ao curso!"
};
