export default {
	OK: "OK",
	accessMaterials: "Åtkomst till material",
	addToMyList: "Lägg till i min lista",
	addedToMyLearningHeader: "Har lagts till i My Learning (mina kurser)",
	addedToYourList: "Tillagd i din lista",
	all: "Alla",
	alreadyEnrolled: "Redan registrerad",
	backToDiscover: "Tillbaka till Upptäck",
	browseAllContent: "Sök bland allt innehåll",
	close: "Stäng",
	continueBrowsing: "Fortsätt att bläddra",
	courseCode: "Kurskod",
	courseDescription: "Kursbeskrivning",
	courseInfo: "Kursinformation",
	coursePageDocumentTitle: "{courseName} - Upptäck - {instanceName}",
	courseSummaryReadyMessage: "{courseTitle} är nu redo",
	discover: "Upptäck",
	discoverHomeMessage: "Det här är hemsidan för Upptäck.",
	discovery: "Discovery",
	durationMinutes: "{minutes} minutes",
	emailFeedback: "Skicka din feedback med e-post till {email}",
	endDate: "Slutdatum",
	endDateIsInThePast: "Den här kursen stängdes {date}.",
	enrollInCourse: "Registrera dig för kursen",
	enrollmentHeaderFail: "Det gick inte att registrera dig",
	enrollmentHeaderPending: "Registreringen är väntande",
	enrollmentHeaderSuccess: "Registreringen slutfördes",
	enrollmentHeaderUnenrolled: "Ingen åtkomst",
	enrollmentMessageFail: "Det gick inte att registrera dig. Försök igen senare.",
	enrollmentMessagePending: "Din registrering till den här kursen är väntande. Om du vill få tillgång till kursen går du tillbaka till den här sidan om ett tag.",
	enrollmentMessageSuccess: "{title} kommer snart att finnas i Mina kurser-widgeten.",
	enrollmentMessageSuccessFuture: "{title} blir tillgänglig i widgeten Mina kurser {date}",
	enrollmentMessageSuccessPast: "{title} avslutades {date}",
	enrollmentMessageUnenrolled: "Du har avregistrerats av en administratör. Om du vill registrera dig igen kontaktar du administratören.",
	enrollmentOptions: "Registreringsalternativ",
	firstPublished: "Publicerades första gången",
	homepageDocumentTitle: "Upptäck - {instanceName}",
	lastUpdatedDate: "Senast uppdaterad {date}",
	loadMore: "Ladda mer",
	message404: "Det uppstod ett 404-fel (sidan saknas).",
	navigateHome: "Tillbaka till startsidan.",
	new: "Ny",
	noActivities: "Det finns inga tillgängliga aktiviteter eller så är du redan registrerad i alla. Försök igen senare.",
	noActivitiesExceptPrmoted: "Det finns inga nya eller uppdaterade aktiviteter tillgängliga eller så är du redan registrerad i alla. Försök igen senare.",
	noCourseDescription: "Ingen kursbeskrivning",
	noResultsHeading: "Inga resultat för \"{searchQuery}\"",
	noResultsMessage: "Prova med ett annat sökord eller {linkStart}Bläddra bland alla{linkEnd} för att visa alla tillgängliga material",
	onMyList: "På min lista",
	openCourse: "Öppna kurs",
	or: "eller",
	pageAllLoadedMessage: "Sidan med kurser har lästs in.",
	pageNext: "Till nästa sida",
	pagePrevious: "Till föregående sida",
	pageSelection: "På sidan {pageCurrent} av {pageTotal}. Ange ett sidnummer för att gå till den sidan",
	pageSelectionInvalid: "Värdet måste vara mellan 1 och {pageTotal}",
	recentlyUpdatedAllLoadedMessage: "Alla nyligen uppdaterade kurser har lästs in",
	resultsFor: "{amount} resultat för \"{searchQuery}\"",
	search: "Sökning",
	searchPlaceholder: "Sök ...",
	searchKeywords: "Sök på nyckelord",
	searchPageDocumentTitle: "Sökning: {searchTerm} - Upptäck - {instanceName}",
	searchResultCount: "{searchResultRange} av {searchResultsTotal} för \"{searchQuery}\"",
	searchResultCountForAllResults: "{searchResultRange} av {searchResultsTotal} resultat",
	searchResultsOffscreen: "Sökresultat för \"{searchQuery}\"",
	searchResultsReadyMessage: "Sida {pageCurrent} av {pageTotal} för \"{searchQuery}\" är nu klar",
	searchResultsReadyMessageForAllResults: "Sida {pageCurrent} av {pageTotal} är nu klar",
	settings: "Inställningar",
	settingsLabel: "Klicka för att visa inställningssidan",
	sorting_enrolled: "Redan registrerad",
	sorting_mostRelevant: "Mest relevant",
	sorting_new: "Ny",
	sorting_sortBy: "Sortera efter",
	sorting_updated: "Uppdaterad",
	startDate: "Startdatum",
	startDateIsInTheFuture: "Den här kursen blir tillgänglig den {date}.",
	startLearning: "Börja inlärning",
	unenroll: "Avregistrera",
	unenrollConfirmBody: "Du har avregistrerats från \"{title}\".",
	unenrollConfirmHeader: "Avregistreringen klar",
	updated: "Uppdaterad",
	viewAll: "Visa alla",
	viewAllLabel: "Klicka för att visa alla aktiviteter",
	viewAllNewLabel: "Klicka för att visa nya aktiviteter",
	viewAllUpdatedLabel: "Klicka för att visa nyligen uppdaterade aktiviteter",
	viewMyList: "Visa min lista",
	welcomeToTheCourse: "Välkommen till kursen!"
};
