export default {
	OK: "Tamam",
	accessMaterials: "Materyallere Eriş",
	addToMyList: "Listeme Ekle",
	addedToMyLearningHeader: "My Learning'e Başarıyla Eklendi",
	addedToYourList: "Listenize eklendi",
	all: "Tümü",
	alreadyEnrolled: "Zaten kayıtlı",
	backToDiscover: "Keşfet'e Geri Dön",
	browseAllContent: "Tüm İçeriklere Göz At",
	close: "Kapat",
	continueBrowsing: "Aramaya Devam Et",
	courseCode: "Ders Kodu",
	courseDescription: "Ders Açıklaması",
	courseInfo: "Ders Bilgileri",
	coursePageDocumentTitle: "{courseName} - Keşfet - {instanceName}",
	courseSummaryReadyMessage: "{courseTitle} artık hazır",
	discover: "Keşfet",
	discoverHomeMessage: "Bu, Keşfet ana sayfasıdır.",
	discovery: "Keşif",
	durationMinutes: "{minutes} dakika",
	emailFeedback: "Geri bildirimlerinizi e-posta ile {email} adresine gönderin",
	endDate: "Bitiş Tarihi",
	endDateIsInThePast: "Bu ders {date} tarihinde kapatıldı.",
	enrollInCourse: "Derse Kaydol",
	enrollmentHeaderFail: "Kayıt Başarısız",
	enrollmentHeaderPending: "Kayıt Bekliyor",
	enrollmentHeaderSuccess: "Kayıt Başarılı",
	enrollmentHeaderUnenrolled: "Geçerli Erişim Yok",
	enrollmentMessageFail: "Kayıt işlemi şu anda gerçekleştirilemiyor, lütfen daha sonra tekrar deneyin.",
	enrollmentMessagePending: "Bu derse kaydınız beklemede, bu derse erişmek için kısa bir süre sonra tekrar kontrol edin.",
	enrollmentMessageSuccess: "{Title} yakında Derslerim pencere öğesinde görülecek.",
	enrollmentMessageSuccessFuture: "{title}, {date} tarihinde Derslerim pencere öğesinde sunulacak",
	enrollmentMessageSuccessPast: "{title}, {date} tarihinde sona erdi",
	enrollmentMessageUnenrolled: "Bir Yönetici tarafından kaydınız silindi. Tekrar kaydolmak için Yöneticinizle iletişime geçin.",
	enrollmentOptions: "Kayıt Seçenekleri",
	firstPublished: "İlk Yayınlanma Tarihi",
	homepageDocumentTitle: "Keşfet - {instanceName}",
	lastUpdatedDate: "Son Güncelleme: {date}",
	loadMore: "Daha Fazla Yükle",
	message404: "Hay aksi! 404 hatası.",
	navigateHome: "Ana sayfaya geri dönün.",
	new: "Yeni",
	noActivities: "Mevcut etkinlik yok veya tümü için kayıt yapmış bulunuyorsunuz. Daha sonra tekrar deneyin.",
	noActivitiesExceptPrmoted: "Mevcut yeni veya güncellenmiş etkinlik yok veya tümü için kayıt yapmış bulunuyorsunuz. Daha sonra tekrar deneyin.",
	noCourseDescription: "Ders açıklaması yok",
	noResultsHeading: "\"{searchQuery}\" araması için sonuç bulunmadı",
	noResultsMessage: "Farklı bir arama terimi kullanmayı deneyin veya mevcut tüm materyalleri görüntülemek için {linkStart}Tümüne Gözat{linkEnd} öğesine tıklayın",
	onMyList: "Listemdekiler",
	openCourse: "Dersi Aç",
	or: "veya",
	pageAllLoadedMessage: "Ders sayfası yüklendi.",
	pageNext: "Sonraki sayfaya git",
	pagePrevious: "Önceki sayfaya git",
	pageSelection: "{pageCurrent}/{pageTotal} numaralı sayfada. İlgili sayfaya gitmek için bir sayfa numarası seçin",
	pageSelectionInvalid: "Değer, 1 ile {pageTotal} arasında olmalıdır",
	recentlyUpdatedAllLoadedMessage: "Yakın zamanda güncellenen tüm dersler yüklendi",
	resultsFor: "\"{searchQuery}\" araması için {amount} sonuç",
	search: "Ara",
	searchPlaceholder: "Ara...",
	searchKeywords: "Anahtar Kelimeleri Ara",
	searchPageDocumentTitle: "Ara: {searchTerm} - Keşfet - {instanceName}",
	searchResultCount: "\"{searchQuery}\" araması için {searchResultRange}/{searchResultsTotal} sonuç",
	searchResultCountForAllResults: "{searchResultRange} / {searchResultsTotal} sonuç",
	searchResultsOffscreen: "\"{searchQuery}\" Arama Sonuçları",
	searchResultsReadyMessage: "\"{searchQuery}\" için {pageCurrent} / {pageTotal}. sayfa artık hazır",
	searchResultsReadyMessageForAllResults: "{pageCurrent} / {pageTotal} artık hazır",
	settings: "Ayarlar",
	settingsLabel: "Ayarlar sayfasını görüntülemek için tıklayın",
	sorting_enrolled: "Zaten Kayıtlı",
	sorting_mostRelevant: "En İlgili",
	sorting_new: "Yeni",
	sorting_sortBy: "Sıralama ölçütü",
	sorting_updated: "Güncellendi",
	startDate: "Başlangıç Tarihi",
	startDateIsInTheFuture: "Bu ders {date} tarihinde kullanıma sunulacak.",
	startLearning: "Öğrenmeye Başla",
	unenroll: "Kaydı Kaldır",
	unenrollConfirmBody: "\"{title}\" kaydından başarıyla çıkarıldınız.",
	unenrollConfirmHeader: "Kayıt Kaldırma Tamamlandı",
	updated: "Güncellendi",
	viewAll: "Tümünü Görüntüle",
	viewAllLabel: "Tüm etkinlikleri görüntülemek için tıklayın",
	viewAllNewLabel: "Yeni etkinlikleri görüntülemek için tıklayın",
	viewAllUpdatedLabel: "Yeni güncellenen etkinlikleri görüntülemek için tıklayın",
	viewMyList: "Listemi görüntüle",
	welcomeToTheCourse: "Derse Hoş Geldiniz!"
};
