export default {
	OK: "确定",
	accessMaterials: "访问材料",
	addToMyList: "添加至我的列表",
	addedToMyLearningHeader: "已成功添加至我的学习",
	addedToYourList: "已添加至您的列表",
	all: "全部",
	alreadyEnrolled: "已注册",
	backToDiscover: "返回“发现”",
	browseAllContent: "浏览所有内容",
	close: "关闭",
	continueBrowsing: "继续浏览",
	courseCode: "课程代码",
	courseDescription: "课程描述",
	courseInfo: "课程信息",
	coursePageDocumentTitle: "{courseName} - 发现 - {instanceName}",
	courseSummaryReadyMessage: "{courseTitle} 现已准备好",
	discover: "发现",
	discoverHomeMessage: "此为“发现”主页。",
	discovery: "发现",
	durationMinutes: "{minutes} 分钟",
	emailFeedback: "将您的反馈通过电子邮件发送至 {email}",
	endDate: "结束日期",
	endDateIsInThePast: "此课程将于 {date} 关闭。",
	enrollInCourse: "注册课程",
	enrollmentHeaderFail: "注册失败",
	enrollmentHeaderPending: "注册处于待定状态",
	enrollmentHeaderSuccess: "已成功注册",
	enrollmentHeaderUnenrolled: "无当前访问",
	enrollmentMessageFail: "此时无法注册，请稍后重试。",
	enrollmentMessagePending: "您对本课程的注册请求正等待批准，请稍后查看以访问本课程。",
	enrollmentMessageSuccess: "即将在“我的课程”微件中推出 {title}。",
	enrollmentMessageSuccessFuture: "即将于 {date} 在“我的课程”微件中推出 {title}",
	enrollmentMessageSuccessPast: "{title} 于 {date} 结束",
	enrollmentMessageUnenrolled: "管理员已取消您的注册，请联系您的管理员以再次注册。",
	enrollmentOptions: "注册选项",
	firstPublished: "首次发布",
	homepageDocumentTitle: "发现 - {instanceName}",
	lastUpdatedDate: "上次更新日期：{date}",
	loadMore: "加载更多",
	message404: "抱歉！出现 404 错误。",
	navigateHome: "返回主页。",
	new: "新建",
	noActivities: "没有可用的活动或者您已注册所有活动。请稍后重试。",
	noActivitiesExceptPrmoted: "没有新的或更新的可用活动或者您已注册所有活动。请稍后重试。",
	noCourseDescription: "无课程描述",
	noResultsHeading: "未找到“{searchQuery}”的结果",
	noResultsMessage: "尝试使用其他搜索词或{linkStart}浏览所有{linkEnd}以查看所有可用材料",
	onMyList: "在我的列表",
	openCourse: "打开课程",
	or: "或",
	pageAllLoadedMessage: "课程页面已加载。",
	pageNext: "至下一页",
	pagePrevious: "至上一页",
	pageSelection: "在第 {pageCurrent}/{pageTotal} 页。输入页码以转到该页",
	pageSelectionInvalid: "值必须在 1 和 {pageTotal} 之间",
	recentlyUpdatedAllLoadedMessage: "已加载最近所有的更新课程",
	resultsFor: "{amount} 条“{searchQuery}”结果",
	search: "搜索",
	searchPlaceholder: "搜索...",
	searchKeywords: "搜索关键字",
	searchPageDocumentTitle: "搜素：{searchTerm} - 发现 - {instanceName}",
	searchResultCount: "{searchResultRange} 条（共 {searchResultsTotal} 条）“{searchQuery}”结果",
	searchResultCountForAllResults: "{searchResultRange} 条结果（共 {searchResultsTotal} 条）",
	searchResultsOffscreen: "搜索“{searchQuery}”的结果",
	searchResultsReadyMessage: "已显示第 {pageCurrent} 页（共 {pageTotal} 页）“{searchQuery}”相关内容",
	searchResultsReadyMessageForAllResults: "已显示第 {pageCurrent} 页（共 {pageTotal} 页）",
	settings: "设置",
	settingsLabel: "点击查看设置页面",
	sorting_enrolled: "已注册",
	sorting_mostRelevant: "最相关",
	sorting_new: "新建",
	sorting_sortBy: "排序方式",
	sorting_updated: "已更新",
	startDate: "开始日期",
	startDateIsInTheFuture: "课程将于 {date} 可用。",
	startLearning: "开始学习",
	unenroll: "取消注册",
	unenrollConfirmBody: "您已成功取消注册“{title}”。",
	unenrollConfirmHeader: "取消注册完成",
	updated: "已更新",
	viewAll: "查看全部",
	viewAllLabel: "点击查看全部活动",
	viewAllNewLabel: "点击查看新活动",
	viewAllUpdatedLabel: "点击查看最新更新的活动",
	viewMyList: "查看我的列表",
	welcomeToTheCourse: "欢迎参加本课程！"
};
